# Site settings
title: Islamic Center of Emporia
email: salim53@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   O People of the Book (Jews and Christians): Come to a word (in good terms) that is just between us and you, that we worship none but God (alone)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.islamiccenteremporia.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
